GroceryHero/Aisles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired


class AisleForm(FlaskForm):
    title = StringField('Name', validators=[DataRequired()])
    content = TextAreaField('Ingredients (separate with commas)', validators=[DataRequired()])
    store = StringField('Store (optional)', validators=[])
    order = SelectField("Aisle Order- the way you go through the store (optional)",
                        choices=[('', '')]+[(str(x), str(x)) for x in range(1, 16)])
    submit = SubmitField('Submit')


class AisleBarForm(FlaskForm):
    aisles = SelectField("Aisle", choices=['No Aisles Yet'], default=['No Aisles Yet'], id=[])
    unadded = SelectMultipleField("Ingredients", choices=['No Ingredients Yet'], default=['No Ingredients Yet'])
    submit = SubmitField('Add')

GroceryHero/Pantry/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, FloatField, FieldList, FormField, SelectMultipleField, StringField, \
    TextAreaField
from wtforms.validators import InputRequired
from GroceryHero.Recipes.utils import Measurements as M


class PantryBarForm(FlaskForm):
    name = SelectField("Name", choices=['No Shelves Yet'], default=['Select a Shelf'])
    content = SelectMultipleField("Ingredients", validators=[InputRequired()])
    ingredient_quantity = FloatField('Quantity', default=1.0, validators=[InputRequired()])
    ingredient_type = SelectField("Measurement", choices=[(x, x) for x in M.Measures], default='Unit')
    add = SubmitField('Add')
    remove = SubmitField('Remove')


class ShelfForm(FlaskForm):
    name = StringField('Shelf Name', validators=[InputRequired()])
    content = TextAreaField('Ingredients (separate with commas)', validators=[InputRequired()])
    submit = SubmitField('Next')


class AddToShelfForm(FlaskForm):
    shelves = SelectField("Shelves", default='[<--Choose-->]')
    multi = SelectMultipleField('Recipe Ingredients')
    other = TextAreaField('Ingredients (separate with commas)', validators=[InputRequired()])
    submit = SubmitField('Next')


class QuantityForm(FlaskForm):
    ingredient_quantity = FloatField('Quantity', default=1.0, validators=[InputRequired()])
    ingredient_type = SelectField("Measurement", choices=M.Measures, default='Unit')


class FullQuantityForm(FlaskForm):
    ingredients = []
    ingredient_forms = FieldList(FormField(QuantityForm), min_entries=1)
    submit = SubmitField('Submit')


class DeleteShelfForm(FlaskForm):
    shelves = SelectMultipleField('Shelves')
    submit = SubmitField('Delete')

GroceryHero/Aisles/routes.py
import string

from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from GroceryHero import db
from GroceryHero.Main.utils import update_grocery_list
from GroceryHero.models import Aisles, Recipes
from GroceryHero.Aisles.forms import AisleForm, AisleBarForm
from GroceryHero.Aisles.utils import GenericAisles

aisles = Blueprint('aisles', __name__)


@aisles.route('/aisles', methods=['GET', 'POST'])
def aisles_page():
    aisle_list = []
    form = AisleBarForm()
    form.unadded.choices = zip(['All Items Sorted!'], ['All Items Sorted!'])
    if current_user.is_authenticated:
        if request.method == 'POST':
            if form.aisles.data != '' and form.aisles.data != 'No Aisles Yet' and form.unadded.data != 'All Items ' \
                                                                                                       'Sorted!':
                aisle = Aisles.query.filter_by(title=form.aisles.data).first()
                content = aisle.content.split(', ')
                if isinstance(form.unadded.data, list):
                    for item in form.unadded.data:
                        content.append(item)
                else:
                    content.append(form.unadded.data)
                aisle.content = ', '.join(sorted(content))
                db.session.commit()
            else:
                return redirect(url_for('aisles.aisles_page'))
        aisle_list = Aisles.query.filter_by(author=current_user).order_by(Aisles.order).all()
        aisle_list = [a for a in aisle_list if a.order > 0] + [a for a in aisle_list if a.order < 1]
        # Ingredients for form that adds unadded ingredients
        aisle_ingredients = set([item for sublist in aisle_list for item in sublist.content.split(', ')])
        if len(aisle_list) > 0:
            form.aisles.choices = [aisle.title for aisle in aisle_list]
        ingredients = [set(recipe.quantity.keys()) for recipe in Recipes.query.filter_by(author=current_user).all()]
        choices = sorted(set([item for sublist in ingredients for item in sublist if item not in aisle_ingredients]))
        form.unadded.choices = [x for x in zip([0] + choices, ['-- select options (clt+click) --'] + choices)]
        if len(form.unadded.choices) < 1:
            form.unadded.choices = zip(['All Items Sorted!'], ['All Items Sorted!'])
    return render_template('aisles.html', aisles=aisle_list, title='Aisles', sidebar=True, form=form, aisle=True)


@aisles.route('/aisles/new', methods=['GET', 'POST'])
@login_required
def new_aisle():
    form = AisleForm()
    if request.method == 'GET':
        choices = get_unique_order_choices(current_user)
        form.order.choices = choices
    if form.validate_on_submit():
        store = form.store.data if form.store.data != '' else None
        order = int(form.order.data) if form.order.data != '' else 0
        form = Aisles(title=string.capwords(form.title.data.strip()), order=order,
                      content=', '.join(set([word.strip().capitalize() for word in form.content.data.split(',')])),
                      store=store, author=current_user)
        db.session.add(form)
        db.session.commit()
        update_grocery_list(current_user)
        flash('Your aisle has been created!', 'success')
        return redirect(url_for('aisles.aisles_page'))
    return render_template('create_aisle.html', title='New Aisle', form=form, legend='New Aisle')


@aisles.route('/aisles/<int:aisle_id>')
def aisle_single(aisle_id):
    aisle_post = Aisles.query.get_or_404(aisle_id)
    return render_template('aisle.html', title=aisle_post.title, aisle=aisle_post)


@aisles.route('/aisles/<int:aisle_id>/update', methods=['GET', 'POST'])
@login_required
def update_aisle(aisle_id):
    aisle = Aisles.query.get_or_404(aisle_id)
    if aisle.author != current_user:  # You can only update your own aisles
        abort(403)
    form = AisleForm()
    if form.validate_on_submit():
        aisle.title = string.capwords(form.title.data)
        aisle.content = ', '.join(set([string.capwords(word.strip()) for word in form.content.data.split(',')]))
        aisle.store = ' '.join([word.strip().capitalize() for word in form.store.data.split(' ')])
        aisle.order = int(form.order.data) if form.order.data != '' else 0
        db.session.commit()  # Don't need to do db.add since we are changing an existing entry
        update_grocery_list(current_user)
        flash('Your aisle has been updated!', 'success')
        return redirect(url_for('aisles.aisle_single', aisle_id=aisle.id))
    elif request.method == 'GET':
        choices = get_unique_order_choices(current_user)
        form.order.choices = [(aisle.order, str(aisle.order))] + choices
        form.order.default = aisle.order
        form.process()
        form.title.data = aisle.title
        form.content.data = aisle.content
        form.store.data = aisle.store
    return render_template('create_aisle.html', title='Update Aisle', form=form, legend='Update Aisle')


@aisles.route('/aisles/<int:aisle_id>/delete', methods=['POST'])
@login_required
def delete_aisle(aisle_id):
    aisle = Aisles.query.get_or_404(aisle_id)
    if aisle.author != current_user:  # You can only update your own aisles
        abort(403)
    db.session.delete(aisle)
    db.session.commit()
    update_grocery_list(current_user)
    flash('Your aisle has been deleted!', 'success')
    return redirect(url_for('aisles.aisles_page'))


@aisles.route('/aisles/download_generic', methods=['POST'])
@login_required
def download_generic():
    pass


def get_unique_order_choices(user):
    aisle_numbers = [x.order for x in Aisles.query.filter_by(user_id=user.id).all()]
    new_numbers, index = [], 1
    while len(new_numbers) < 5:
        if index not in aisle_numbers:
            new_numbers.append(index)
        index += 1
    return [(0, 'No Order')] + [(x, x) for x in new_numbers]

GroceryHero/Pantry/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required

from GroceryHero.Main.forms import ExtrasForm
from GroceryHero.Main.utils import convert_frac
from GroceryHero.Pantry.utils import add_pantry
from GroceryHero.Pantry.forms import PantryBarForm, FullQuantityForm, ShelfForm, DeleteShelfForm, AddToShelfForm
from GroceryHero.Recipes.utils import Measurements
from GroceryHero.models import Recipes
from GroceryHero import db
import string
import json

pantry = Blueprint('pantry', __name__)


@pantry.route('/pantry', methods=['GET', 'POST'])
def pantry_page():
    form = PantryBarForm()
    if current_user.is_authenticated:
        if current_user.pantry is None:
            current_user.pantry = {}
            db.session.commit()
        # # {Shelf: {Ingredient: [quantity, unit],...},...}
        all_pantry = current_user.pantry
        for shelf in all_pantry:
            all_pantry[shelf] = {k: all_pantry[shelf][k] for k in sorted(all_pantry[shelf])}
        all_pantry = {name: {ing: Measurements(value=int(L[0]) if float(L[0]).is_integer() else L[0], unit=L[1])
                             for ing, L in all_pantry[name].items()}
                      for name, ing in all_pantry.items()}
        # Sidebar adding choices
        ingredients = [recipe.quantity.keys() for recipe in Recipes.query.filter_by(author=current_user)]  # Ingredients
        ingredients = ingredients + [current_user.pantry[item] for item in [key for key in current_user.pantry]]
        form.content.choices = [(x, x) for x in sorted(set(item for sublist in ingredients for item in sublist))]
        form.name.choices = [(x, x) for x in all_pantry.keys()]
        if form.validate_on_submit():
            shelf = form.name.data
            ingredients = {ing: [form.ingredient_quantity.data, form.ingredient_type.data] for ing in form.content.data}
            add_pantry(current_user, ingredients, shelf, form.add.data)
            all_pantry = current_user.pantry
            all_pantry = {name: {ing: Measurements(value=int(L[0]) if float(L[0]).is_integer() else L[0], unit=L[1])
                                 for ing, L in all_pantry[name].items()}
                          for name, ing in all_pantry.items()}
    else:
        all_pantry = []
        form.content.choices = [('No Ingredients Yet', 'No Ingredients Yet')]
    return render_template('pantry.html', title='Pantry', sidebar=True, pantry=True, form=form, shelves=all_pantry)


@login_required
@pantry.route('/new_shelf', methods=['GET', 'POST'])
def new_shelf():
    form = ShelfForm()
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    else:
        if form.validate_on_submit():  # Send data to quantity page
            ingredients = sorted([string.capwords(x.strip()) for x in form.content.data.split(',') if x.strip() != ''])
            quantity = {ingredient: [1, 'Unit'] for ingredient in ingredients}
            send = json.dumps({'name': form.name.data, 'quantity': quantity})
            return redirect(url_for('pantry.new_shelf_quantity', send=send))
    return render_template('new_shelf.html', title='Pantry', legend='New Shelf', form=form)


@pantry.route('/new_shelf/<string:send>', methods=['GET', 'POST'])
@login_required
def new_shelf_quantity(send):
    send = json.loads(send)  # Has {RecipeName: string, Quantity: {ingredient: [value,type]}}
    shelf_name = string.capwords(send['name'].strip())
    data = {'ingredient_forms': [{'ingredient_quantity': send['quantity'][ingredient][0],
                                  'ingredient_type': send['quantity'][ingredient][1]}
                                 for ingredient in send['quantity'].keys()]}
    form = FullQuantityForm(data=data)
    form.ingredients = [x for x in send['quantity'].keys()]
    if form.is_submitted():  # change to validate
        quantity = [data['ingredient_quantity'] for data in form.ingredient_forms.data]
        measure = [data['ingredient_type'] for data in form.ingredient_forms.data]
        formatted = {ingredient: [int(Q), M] for ingredient, Q, M in zip(form.ingredients, quantity, measure)}
        copy = current_user.pantry.copy()
        copy[shelf_name] = formatted
        current_user.pantry = copy
        db.session.commit()
        flash('Your shelf has been created!', 'success')
        return redirect(url_for('pantry.pantry_page'))
    return render_template('new_shelf_quantity.html', title='New Shelf', form=form, legend='Ingredient Quantities',
                           recipe=send)


@pantry.route('/delete_shelf', methods=['GET', 'POST'])
def delete_shelf():
    shelves = current_user.pantry.copy()
    if len(shelves) < 1:
        return redirect(url_for('pantry.pantry_page'))
    form = DeleteShelfForm()
    form.shelves.choices = [(x, x) for x in shelves]
    if form.validate_on_submit():
        deletes = form.shelves.data
        for delete in deletes:
            del shelves[delete]
        current_user.pantry = {}  # todo ?double needed
        db.session.commit()
        current_user.pantry = shelves
        db.session.commit()
        return redirect(url_for('pantry.pantry_page'))
    return render_template('delete_shelf.html', title='Pantry', legend='Delete Shelves', form=form)


@pantry.route('/add_to_shelf', methods=['GET', 'POST'])
def add_to_shelf():
    form = AddToShelfForm()
    shelves = current_user.pantry.copy()
    if len(shelves) < 1:
        return redirect(url_for('pantry.pantry_page'))
    ingredients = [list(x.quantity.keys()) for x in Recipes.query.filter_by(author=current_user).all()]
    shelf_ings = [list(shelves[shelf].keys()) for shelf in shelves]
    ingredients = sorted(set([item for sublist in ingredients+shelf_ings for item in sublist]))
    form.multi.choices = [('', 'Ingredients Choices')] + [(choice, choice) for choice in ingredients]
    form.shelves.choices = [('', 'Shelf Choices')] + [(x, x) for x in shelves.keys()]
    if form.validate_on_submit():  # Form is submitted and not empty list
        form.other.data.split(', ')
        choices = form.multi.data
        if form.other.data != '':
            choices = choices + [string.capwords(x.strip()) for x in form.other.data.split(', ') if x.strip() != '']
        if choices == '':  # No selection  # todo add this to
            return redirect(url_for('main.add_to_extras'))
        choices = json.dumps(choices)
        return redirect(url_for('pantry.shelf_add', ingredients=choices))
    return render_template('add_extras.html', legend='Add To Shelves', form=form, ingredients=True, shelves=True)


@pantry.route('/shelf_add/<ingredients>', methods=['GET', 'POST'])
def shelf_add(ingredients):
    ingredients = json.loads(ingredients)
    data = {'ingredient_forms': [{f'ingredient_quantity': 1.0, f'ingredient_type': 'Unit'}
                                 for _ in ingredients]}
    form = FullQuantityForm(data=data)  # List of dictionaries
    form.ingredients = ingredients
    shelves = current_user.pantry
    # print(form.validate())
    if form.validate_on_submit():
        # user.grocery_list [{'Another Name': [['Bread Crumbs', 1, 'Unit', 0], ...], 'Alex': []}, overlap[int]]
        # Extras list Format: [ [AisleName, [IngredientName, quantity, unit, BoolCheck]],...]
        entries = []
        for i, ingredient_form in enumerate(form.ingredient_forms):  # For item in user entered extras
            for j, shelf in enumerate(shelves):  # For aisle in user aisles
                if form.ingredients[i] in shelves[shelf].keys() and j <= len(shelves):  # If ingredient in that aisle
                    entries.append([shelf, [form.ingredients[i],
                                            convert_frac(ingredient_form.ingredient_quantity.data),
                                            ingredient_form.ingredient_type.data, 0]])  # Add to extras
                    break
        # print(entries)
        # db.session.commit()
        return redirect(url_for('pantry.pantry_page'))
    return render_template('add_extras.html', legend='Add Their Units', form=form, add=True)


@pantry.route('/compatible_recipes', methods=['GET'])
@login_required
def compatible_recipes(ings, algo=1):
    # algo_dict = {0: 'Charity', 1: 'Fairness', 2: 'Balanced', 3: 'Selfish', 4: 'Greedy'}
    # algorithm = algo_dict[algo]
    recipe_ids = {r.id: r for r in Recipes.query.all()}
    recipes_dict = {r.id: [x.lower() for x in r.quantity.keys()] for r in recipe_ids.values()}

    scores = [[recipe_ids[rid], sum(1 for ing in ings if ing in ingredients)]
              for rid, ingredients in recipes_dict.items()]

    # scores = [[recipe_ids[rid],
    #            norm_stack({rid: ingredients, 0: ings}, algorithm=algorithm)]
    #           for rid, ingredients in recipes_dict.items()]
    if scores:
        recommendations = sorted(scores, key=lambda x: x[1], reverse=True)
        recommendations = [x for x in recommendations if x[1] > 0]
        return recommendations
    else:
        return

GroceryHero/templates/about.html
{% extends 'layout.html' %}
{% block content %}
<body>
  <h1>About</h1>
  <div class="content-section mt-3">
      <legend class="border-bottom mb-3">Tips to Being a Grocery Hero</legend>
      <ul class="mb-3">
        <li>Ingredients that are metric and ones that are Imperial will not combine in the grocery list as of currently.
          If you have 1 pound of chicken and 100 grams of chicken, they will stay separated.
        </li>
        <li>Recipe ingredients have 3 unit types: generic, weight, or volume. When your grocery list is made ingredients
          that are of the same type can be combined, ie rice 1 cup + rice 2 cups = rice 3 cups. This is also valid:
          sugar 15 tablespoons + sugar 1 tablespoon = sugar 1 cup. It will combine to the highest unit within that type.
          However generic units do not have that ability. Egg 1 jar + egg 1 package = egg 1 unit, egg 1 package since
          there is no conversion possible from jars to packages/cans/bottles and etc.
        </li>
        <li>You can only clear your menu when you have eaten everything on your menu, otherwise remove it from the
          recipes page.</li>
        <li>Adding a friends recipe to your menu is in fact borrowing the same copy of that recipe. Whatever change they make to it
          will change it for you as well. You can download their recipe but with your own copy the number of times that recipe will not
          be updated for that recipe and instead to your copy and their copy separately.</li>
      </ul>
    </div>
    <div class="content-section mt-3">
    <legend class="border-bottom mb-3">On This Version</legend>
      <h5 class="mt-3">What's new?</h5>
      <ul class="mt-2 mb-2">
        <li>To be filled in.</li>
      </ul>
    <h5 class="mt-3">What's coming up?</h5>
    <ul class="mt-2 mb-2">
      <li>To be filled in.</li>
    </ul>
  </div>
  {% if current_user.pro %}
    <section id="harmonytool">
      <div class="content-section mt-3">
        <legend class="border-bottom mb-3">Recipe Harmony Tool FAQs</legend>
        <h5 class="mt-3">What is the Recipe Harmony Tool?</h5>
        <p class="mt-2 mb-2">The Recipe Harmony Tool is a way of grouping recipes together that overlap in
          ingredients so that buying in bulk and preventing food waste is easier; saving you money and in a small
          way, helping the earth. It can evaluate anywhere from hundreds to millions of recipe combinations
          and recommend the top 3 that fit your specific preferences.
        </p>
        <h5 class="mt-3">What is the meaning of the Recipe Harmony Score?</h5>
        <p class="mt-2 mb-2">The harmony score is a way to measure how similar a group of recipes are by their
          shared ingredients. But that's not the only thing it can consider. By adding utilizing some of the advanced
          harmony settings in your account page the harmony score can consider which ingredients you do or do not want
          to see very often, which recipes you want or don't want together and more; all of which will affect the
          harmony score. After configuring these settings it may be possible to achieve a score higher than 100%.
        </p>
        <h5 class="mt-3" id="advanced">What is a good Recipe Harmony Score?</h5>
        <p>Generally, anything lower than 20 means there are next to no ingredient overlap while anything above 70
          means they are practically the same recipe. A score of 100% is possible but only for completely
          identical recipes. From my experience a group score higher than 50% tends to taste very similar but with
          advanced settings configured that can be avoided. By configuring those it may be possible to get a score
          higher than 100%!
        </p>
        <h5 class="mt-3">What is the Harmony Mode setting in the advanced settings?</h5>
        <p>If you have 3 apples, 1 ground beef, 2 yogurts, and 4 sodas on your grocery list, this is how the modes would each interact.
        <ul class="">
          <li>Charity only wants to make the weakest link (ground beef in this case) as big as possible</li>
          <li>Fairness wants every item to be the same quantity (increase ground beef, then yogurt then apples) and then increase them evenly</li>
          <li>Balanced and Selfish want all items to get bigger but</li>
          <li>Selfish with an even higher priority towards the bigger items than balanced.</li>
          <li>Greedy only wants the largest quantity item (sodas in this case) as big as possible.</li>
        </ul></p>
      </div>
    {% endif %}
</body>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Are you sure you'd like to import recipes?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

GroceryHero/templates/aisles.html
{% extends 'layout.html' %}
{% block content %}
<div class="mb-4">
    <h1 style="display: inline" class="">Your Aisles</h1>
    <a style="display: inline; float:right" class="btn btn-sm btn-info mt-3" href="{{ url_for('aisles.new_aisle') }}">New Aisle</a>
</div>
{% if aisles[0] is not defined and aisles[0] != '' %}
    <div class="card">
        <div class="card-header p-0" id="headingMenu">
            <h5 class="mb-0">
                <button style=".collapse" class="btn btn-light btn-block" data-toggle="collapse" data-target="#collapseMenu"  aria-controls="collapseMenu">
                   {% if current_user.is_authenticated %}
                     <a style="text-decoration:none; color: grey;" href="{{ url_for('aisles.new_aisle') }}">You have no aisles yet. Click to add an aisle.</a>
                   {% else %}
                     <a style="text-decoration:none; color: grey;" href="{{ url_for('users.auth_login') }}">You have no aisles yet. Login to add an aisle.</a>
                   {% endif %}
                </button>
            </h5>
        </div>
    </div>
{% else %}
    <div class="mb-2">
        <p class="text-muted" style="display:inline;">You have {{ aisles|length }} aisle(s)</p>
    </div>
    {% for aisle in aisles %}
        <article class="media content-section">
            {% if aisle.order > 9 %}
                <h4 class="text-muted mr-2">{{ aisle.order }}</h4>
            {% elif aisle.order != 0 %}
                <h2 class="text-muted mr-3">{{ aisle.order }}</h2>
            {% else %}
                <h2 class="text-muted mr-4 pr-2"></h2>
            {% endif %}
            <div class="media-body">
                <div class="article-metadata">
                    <a style="font-size: 18px;" class="mr-2" href="{{ url_for('aisles.aisle_single', aisle_id=aisle.id) }}">{{ aisle.title }}</a>
                    {% if aisle.store %}
                        <small style="font-size:15px; float:right;">Store: {{ aisle.store }} </small>
                    {% endif %}
                </div>
                <p class="article-content">{{ aisle.content }}</p>

            </div>
        </article>
    {% endfor %}
{% endif %}
{% endblock content %}

GroceryHero/templates/pantry.html
{% extends 'layout.html' %}
{% block content %}
<div class="mb-4">
    <h1 style="display: inline">Your {{ title }}</h1>
    <a style="display: inline; float:right" class="btn btn-sm btn-info mt-3" href="{{ url_for('pantry.new_shelf') }}">New Shelf</a>
</div>
  <div class="content-section pl-3">
    <!-- <div class="mb-4 d-none d-md-block d-lg-block d-xl-block">-->
    <div class="mb-4">
      <h4 style="display:inline;">Shelves</h4>
      <div style="float:right" class="justify-content-right d-flex"> {# The two buttons #}
        <a class="btn btn-outline-success btn-sm mr-2" href="{{ url_for('pantry.add_to_shelf') }}">Add To</a>
        <form action="{{ url_for('pantry.delete_shelf') }}">
            <button class="btn btn-outline-danger btn-sm">Delete Shelf</button>
        </form>
      </div>
    </div>
{#      <!-- </div>-->#}
{#      <!-- Shelves section MOBILE-->#}
{#      <!-- <div class="mb-3 d-block d-sm-none row">-->#}
{#      <!-- <h3 class="col-12 mt-2 mb-2 text-center">Pantry Shelves</h3>-->#}
{#      <!-- <div class="border-bottom pb-1 col-12 justify-content-center d-flex">-->#}
{#      <!-- <form class="mb-2" action="#">-->#}
{#      <!--     <button class="btn btn-outline-success btn-sm">Add Shelf</button>-->#}
{#      <!-- </form>-->#}
{#      <!-- <form class="ml-2" action="#">-->#}
{#      <!--     <button class="btn btn-outline-danger btn-sm">Clear Shelves</button>-->#}
{#      <!-- </form>-->#}
{#      <!--   </div>-->#}
{#      <!--  </div>-->#}
      {% if shelves|length < 1 %}
        <div class="card my-3">
          <div class="card-header p-0" id="headingMenu">
            <h5 class="mb-0">
              <button style=".collapse" class="btn btn-light btn-block" data-toggle="collapse" data-target="#collapseMenu"  aria-controls="collapseMenu">
                {% if current_user.is_authenticated %}
                  <a style="text-decoration:none; color: grey;" href="{{ url_for('pantry.new_shelf') }}">You have no shelves yet. Click to add a shelf.</a>
                {% else %}
                   <a style="text-decoration:none; color: grey;" href="{{ url_for('users.auth_login') }}">You have no shelves yet. Login to add an shelf.</a>
                {% endif %}
              </button>
            </h5>
          </div>
        </div>
      {% else %}
        <div class="mb-3">
        {% for shelf in shelves %}
          <div class="card">
            <!--Button-->
            <div class="card-body bg-success p-0" id="{{ shelf }}">
              <h5 class="mb-0">
                <button style=".collapse" class="btn btn-success btn-block pl-0" data-toggle="collapse" data-target="#collapse{{ shelf }}"  aria-controls="collapse{{ shelf }}">
                {{ shelf }}
                </button>
              </h5>
            </div>
            <!--Info section-->
            <div id="collapse{{ shelf }}" class="collapse {% if shelves[shelf]|length > 0%}show{% endif %}" aria-labelledby="heading{{ shelf }}" data-parent="#accordion">
              <div class="card-body mt-3 ml-4">
                <!-- <div class="border-bottom mr-3 mb-1 pb-1 pt-0">-->
                  <!-- <a>Items:</a>-->
                <!-- </div>-->
                <ul>
                  {% if shelves[shelf]|length < 1%}
                       <li>This shelf is empty</li>
                   {% endif %}
                  {% for ingredient in shelves[shelf] %}
                      <li>{{ ingredient }} <i style="font-size: 14px;">{{ shelves[shelf][ingredient].value }} {{ shelves[shelf][ingredient].unit.lower() }}{% if shelves[shelf][ingredient].value != 1 %}s{% endif %}</i></li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock content %}